/**
 * Centralized Artificial Satellites & Spacecraft Dataset for COSMOS
 * All artificial satellites render as sleek small glowing dots around their parent bodies.
 */

export const ARTIFICIAL_SATELLITES_DATA = [
  // ============================================================
  // SPACE AGE PIONEERS (1957–1970)
  // ============================================================
  {
    id: 'sputnik-1',
    name: 'Sputnik 1',
    wikipediaTitle: 'Sputnik 1',
    category: 'artificial',
    layer: 'pioneers',
    parentBodyId: 'earth',
    launchYear: 1957,
    countryAgency: 'USSR',
    missionType: 'Technology Demonstration / Science',
    orbitType: 'Low Earth Orbit (LEO)',
    visualTemplate: 'pioneer',
    color: 0x38bdf8,
    orbitalDistance: 4.2,
    orbitalPeriodDays: 0.0668,
    M0: 0.5,
    orbitSpeed: 2.4,
    rotationSpeed: 0.02,
    diameter: '58 cm sphere',
    orbitalPeriod: '96.2 minutes',
    status: 'Completed Mission (Re-entered 1958)',
    description: 'First artificial satellite in human history; launched by the USSR on October 4, 1957, triggering the Space Age.',
    significance: 'Offered the first space-based radio telemetry and opened human space exploration.'
  },
  {
    id: 'sputnik-2',
    name: 'Sputnik 2',
    wikipediaTitle: 'Sputnik 2',
    category: 'artificial',
    layer: 'pioneers',
    parentBodyId: 'earth',
    launchYear: 1957,
    countryAgency: 'USSR',
    missionType: 'Biological Spaceflight',
    orbitType: 'Low Earth Orbit (LEO)',
    visualTemplate: 'pioneer',
    color: 0xa1a1aa,
    orbitalDistance: 4.8,
    orbitalPeriodDays: 0.0720,
    M0: 1.2,
    orbitSpeed: 2.2,
    rotationSpeed: 0.015,
    diameter: '4 meters capsule',
    orbitalPeriod: '103.7 minutes',
    status: 'Completed Mission',
    description: 'Second spacecraft launched into Earth orbit; carried Laika the dog, the first living creature in orbit.',
    significance: 'Pioneered biological spaceflight data for human space travel.'
  },
  {
    id: 'explorer-1',
    name: 'Explorer 1',
    wikipediaTitle: 'Explorer 1',
    category: 'artificial',
    layer: 'pioneers',
    parentBodyId: 'earth',
    launchYear: 1958,
    countryAgency: 'USA / ABMA / JPL',
    missionType: 'Cosmic Ray Detection',
    orbitType: 'Medium Earth Orbit',
    visualTemplate: 'pioneer',
    color: 0x38bdf8,
    orbitalDistance: 5.4,
    orbitalPeriodDays: 0.0797,
    M0: 2.1,
    orbitSpeed: 2.0,
    rotationSpeed: 0.03,
    diameter: '2.03 m cylinder',
    orbitalPeriod: '114.8 minutes',
    status: 'Completed Mission (Re-entered 1970)',
    description: 'The first satellite launched by the United States. Designed by James Van Allen and built by JPL.',
    significance: 'Discovered the Van Allen radiation belts surrounding Earth.'
  },
  {
    id: 'vanguard-1',
    name: 'Vanguard 1',
    wikipediaTitle: 'Vanguard 1',
    category: 'artificial',
    layer: 'pioneers',
    parentBodyId: 'earth',
    launchYear: 1958,
    countryAgency: 'USA / US Navy',
    missionType: 'Solar Power Test & Geodesy',
    orbitType: 'Medium Earth Orbit',
    visualTemplate: 'pioneer',
    color: 0xfbbf24,
    orbitalDistance: 6.0,
    orbitalPeriodDays: 0.0932,
    M0: 3.4,
    orbitSpeed: 1.8,
    rotationSpeed: 0.02,
    diameter: '16.5 cm sphere',
    orbitalPeriod: '134.2 minutes',
    status: 'Inactive (Oldest human object still in orbit)',
    description: "World's first solar-powered satellite. Though silent since 1964, it remains the oldest artificial object orbiting Earth.",
    significance: 'Proved the utility of solar cells for satellite power and determined Earth is slightly pear-shaped.'
  },
  {
    id: 'telstar-1',
    name: 'Telstar 1',
    wikipediaTitle: 'Telstar',
    category: 'artificial',
    layer: 'pioneers',
    parentBodyId: 'earth',
    launchYear: 1962,
    countryAgency: 'USA / AT&T Bell Labs',
    missionType: 'Communications',
    orbitType: 'Elliptical Medium Earth Orbit',
    visualTemplate: 'pioneer',
    color: 0x60a5fa,
    orbitalDistance: 6.8,
    orbitalPeriodDays: 0.1097,
    M0: 4.1,
    orbitSpeed: 1.6,
    rotationSpeed: 0.02,
    diameter: '88 cm sphere',
    orbitalPeriod: '157.8 minutes',
    status: 'Inactive',
    description: 'First active direct-relay communications satellite. Relayed the first live transatlantic television pictures.',
    significance: 'Began the modern satellite communications industry.'
  },

  // ============================================================
  // MODERN EARTH ORBIT & SPACE STATIONS
  // ============================================================
  {
    id: 'iss',
    name: 'International Space Station',
    wikipediaTitle: 'International Space Station',
    category: 'artificial',
    layer: 'earth-sats',
    parentBodyId: 'earth',
    launchYear: 1998,
    countryAgency: 'NASA / Roscosmos / ESA / JAXA / CSA',
    missionType: 'Orbital Microgravity Laboratory',
    orbitType: 'Low Earth Orbit (LEO, 418 km)',
    visualTemplate: 'radar',
    color: 0x38bdf8,
    orbitalDistance: 3.6,
    orbitalPeriodDays: 0.0645,
    M0: 1.8,
    orbitSpeed: 2.8,
    rotationSpeed: 0.005,
    diameter: '109 m x 73 m (Truss and Solar Arrays)',
    orbitalPeriod: '92.9 minutes',
    status: 'Active (Continuously inhabited since Nov 2000)',
    description: 'The largest artificial structure in space, orbiting Earth every 90 minutes. A joint international laboratory advancing microgravity research, medicine, and human spaceflight technology.',
    significance: 'Continuous human presence in space for over 23 years.'
  },
  {
    id: 'tiangong',
    name: 'Tiangong Space Station',
    wikipediaTitle: 'Tiangong space station',
    category: 'artificial',
    layer: 'earth-sats',
    parentBodyId: 'earth',
    launchYear: 2021,
    countryAgency: 'China (CMSA)',
    missionType: 'Modular Space Station',
    orbitType: 'Low Earth Orbit (LEO, 390 km)',
    visualTemplate: 'radar',
    color: 0xef4444,
    orbitalDistance: 3.9,
    orbitalPeriodDays: 0.0638,
    M0: 3.2,
    orbitSpeed: 2.7,
    rotationSpeed: 0.005,
    diameter: '55 m T-shaped modular station',
    orbitalPeriod: '91.9 minutes',
    status: 'Active (Permanently Crewed)',
    description: "China's modular space station in Low Earth Orbit consisting of the Tianhe core module and Wentian and Mengtian science lab modules.",
    significance: "China's first long-term orbital space station."
  },
  {
    id: 'hubble',
    name: 'Hubble Space Telescope',
    wikipediaTitle: 'Hubble Space Telescope',
    category: 'artificial',
    layer: 'earth-sats',
    parentBodyId: 'earth',
    launchYear: 1990,
    countryAgency: 'NASA / ESA',
    missionType: 'Space Astronomy Observatory',
    orbitType: 'Low Earth Orbit (LEO, 540 km)',
    visualTemplate: 'telescope',
    color: 0x38bdf8,
    orbitalDistance: 4.5,
    orbitalPeriodDays: 0.0662,
    M0: 5.1,
    orbitSpeed: 2.5,
    rotationSpeed: 0.003,
    diameter: '13.2 m length, 2.4 m primary mirror',
    orbitalPeriod: '95.4 minutes',
    status: 'Active (Over 33 years in orbit)',
    description: 'One of the most famous scientific instruments in history. Positioned above Earth\'s distorting atmosphere, Hubble has captured over 1.5 million deep space observations.',
    significance: 'Helped pin down the age of the Universe and confirmed the acceleration of cosmic expansion.'
  },
  {
    id: 'starlink-swarm-1',
    name: 'Starlink Constellation (LEO Alpha)',
    wikipediaTitle: 'Starlink',
    category: 'artificial',
    layer: 'constellations',
    parentBodyId: 'earth',
    launchYear: 2019,
    countryAgency: 'SpaceX',
    missionType: 'Global Satellite Internet',
    orbitType: 'Low Earth Orbit (550 km)',
    visualTemplate: 'pioneer',
    color: 0x22c55e,
    orbitalDistance: 3.4,
    orbitalPeriodDays: 0.065,
    M0: 0.8,
    orbitSpeed: 2.9,
    rotationSpeed: 0.01,
    diameter: 'Flat-panel constellation unit',
    orbitalPeriod: '95 minutes',
    status: 'Active Megaconstellation',
    description: 'Part of SpaceX\'s satellite constellation providing high-speed low-latency broadband internet across the globe.',
    significance: 'World\'s largest satellite constellation in LEO.'
  },
  {
    id: 'starlink-swarm-2',
    name: 'Starlink Constellation (LEO Beta)',
    wikipediaTitle: 'Starlink',
    category: 'artificial',
    layer: 'constellations',
    parentBodyId: 'earth',
    launchYear: 2021,
    countryAgency: 'SpaceX',
    missionType: 'Global Satellite Internet',
    orbitType: 'Low Earth Orbit (540 km)',
    visualTemplate: 'pioneer',
    color: 0x10b981,
    orbitalDistance: 3.5,
    orbitalPeriodDays: 0.065,
    M0: 3.8,
    orbitSpeed: 2.9,
    rotationSpeed: 0.01,
    diameter: 'Flat-panel unit',
    orbitalPeriod: '95 minutes',
    status: 'Active Megaconstellation',
    description: 'Second orbital plane of Starlink communication nodes providing global coverage.',
    significance: 'Pioneered mass-manufactured satellite mega-constellations.'
  },
  {
    id: 'gps-iii',
    name: 'GPS III Navigation Satellite',
    wikipediaTitle: 'Global Positioning System',
    category: 'artificial',
    layer: 'constellations',
    parentBodyId: 'earth',
    launchYear: 2018,
    countryAgency: 'US Space Force',
    missionType: 'Global Navigation & Timing',
    orbitType: 'Medium Earth Orbit (MEO, 20,200 km)',
    visualTemplate: 'pioneer',
    color: 0xf59e0b,
    orbitalDistance: 7.2,
    orbitalPeriodDays: 0.5,
    M0: 2.5,
    orbitSpeed: 1.4,
    rotationSpeed: 0.01,
    diameter: '3.8 m satellite bus',
    orbitalPeriod: '11.97 hours',
    status: 'Active',
    description: 'Next-generation Global Positioning System satellite providing 3x better accuracy and 8x improved anti-jamming capabilities worldwide.',
    significance: 'Critical global infrastructure powering global navigation and precise timing.'
  },

  // ============================================================
  // LUNAR SPACECRAFT & HISTORIC MOON MISSIONS
  // ============================================================
  {
    id: 'chandrayaan-1',
    name: 'Chandrayaan-1',
    wikipediaTitle: 'Chandrayaan-1',
    category: 'artificial',
    layer: 'deep-space',
    parentBodyId: 'earth',
    launchYear: 2008,
    countryAgency: 'India (ISRO)',
    missionType: 'Lunar Orbiter & Impactor',
    orbitType: 'Polar Lunar Orbit',
    visualTemplate: 'probe',
    color: 0xf97316,
    orbitalDistance: 5.0,
    orbitalPeriodDays: 0.08,
    M0: 1.1,
    orbitSpeed: 2.0,
    rotationSpeed: 0.01,
    diameter: '1.5 m cube bus',
    orbitalPeriod: '2 hours',
    status: 'Completed Mission',
    description: "India's first mission to the Moon. Carried the Moon Impact Probe (MIP) which struck Shackleton crater at the lunar south pole.",
    significance: 'Made the landmark discovery of widespread water molecules (H2O/OH) bound to the lunar soil using the M3 payload.'
  },
  {
    id: 'chandrayaan-2',
    name: 'Chandrayaan-2 Orbiter',
    wikipediaTitle: 'Chandrayaan-2',
    category: 'artificial',
    layer: 'deep-space',
    parentBodyId: 'earth',
    launchYear: 2019,
    countryAgency: 'India (ISRO)',
    missionType: 'Lunar Remote Sensing Orbiter',
    orbitType: 'Polar Lunar Orbit (100 km)',
    visualTemplate: 'probe',
    color: 0xf97316,
    orbitalDistance: 5.2,
    orbitalPeriodDays: 0.08,
    M0: 3.5,
    orbitSpeed: 1.9,
    rotationSpeed: 0.01,
    diameter: '3.1 m spacecraft bus',
    orbitalPeriod: '2 hours',
    status: 'Active (Orbiter operational)',
    description: "Advanced Indian lunar orbiter carrying 8 high-resolution scientific instruments mapping water ice, minerals, and terrain elevation.",
    significance: 'Highest-resolution camera (OHRC) ever placed in orbit around the Moon.'
  },
  {
    id: 'chandrayaan-3',
    name: 'Chandrayaan-3 (Vikram / Pragyan)',
    wikipediaTitle: 'Chandrayaan-3',
    category: 'artificial',
    layer: 'deep-space',
    parentBodyId: 'earth',
    launchYear: 2023,
    countryAgency: 'India (ISRO)',
    missionType: 'Lunar South Pole Soft Landing & Rover',
    orbitType: 'Lunar South Pole Surface / Orbit',
    visualTemplate: 'probe',
    color: 0xf97316,
    orbitalDistance: 5.4,
    orbitalPeriodDays: 0.08,
    M0: 5.2,
    orbitSpeed: 1.8,
    rotationSpeed: 0.01,
    diameter: 'Propulsion Module & Lander/Rover unit',
    orbitalPeriod: '2 hours',
    status: 'Completed Mission Objectives (Historic Landing Aug 23, 2023)',
    description: "Historic Indian mission that achieved the world's first successful soft landing near the lunar south pole on August 23, 2023.",
    significance: 'Made India the 4th country to soft-land on the Moon and 1st to land near the lunar south pole.'
  },
  {
    id: 'lro',
    name: 'Lunar Reconnaissance Orbiter (LRO)',
    wikipediaTitle: 'Lunar Reconnaissance Orbiter',
    category: 'artificial',
    layer: 'deep-space',
    parentBodyId: 'earth',
    launchYear: 2009,
    countryAgency: 'NASA',
    missionType: 'Lunar Topography & Resource Mapping',
    orbitType: 'Polar Lunar Orbit',
    visualTemplate: 'probe',
    color: 0x38bdf8,
    orbitalDistance: 5.6,
    orbitalPeriodDays: 0.08,
    M0: 2.3,
    orbitSpeed: 1.7,
    rotationSpeed: 0.01,
    diameter: '2.7 m x 2.6 m satellite bus',
    orbitalPeriod: '2 hours',
    status: 'Active (Mapping Moon since 2009)',
    description: "NASA robotic spacecraft creating the most detailed 3D topographic maps of the lunar surface, cratering history, and cold traps.",
    significance: 'Returned sub-meter resolution imagery of Apollo landing sites and permanently shadowed craters.'
  },

  // ============================================================
  // MARS SPACECRAFT & INTERPLANETARY PROBES
  // ============================================================
  {
    id: 'mangalyaan',
    name: 'Mangalyaan (Mars Orbiter Mission)',
    wikipediaTitle: 'Mars Orbiter Mission',
    category: 'artificial',
    layer: 'deep-space',
    parentBodyId: 'mars',
    launchYear: 2013,
    countryAgency: 'India (ISRO)',
    missionType: 'Martian Atmospheric & Surface Exploration',
    orbitType: 'Elliptical Mars Orbit',
    visualTemplate: 'probe',
    color: 0xf97316,
    orbitalDistance: 4.2,
    orbitalPeriodDays: 3.15,
    M0: 0.7,
    orbitSpeed: 2.1,
    rotationSpeed: 0.01,
    diameter: '1.5 m cube bus with 1.8 m solar array',
    orbitalPeriod: '72.9 hours',
    status: 'Completed Mission (2014–2022)',
    description: "India's first interplanetary mission. Inserted into Mars orbit on September 24, 2014, making ISRO the 4th space agency to reach Mars.",
    significance: 'Achieved Mars orbit on first attempt at a record low cost of $74 million.'
  },
  {
    id: 'perseverance',
    name: 'Perseverance & Ingenuity',
    wikipediaTitle: 'Perseverance (rover)',
    category: 'artificial',
    layer: 'deep-space',
    parentBodyId: 'mars',
    launchYear: 2020,
    countryAgency: 'NASA / JPL',
    missionType: 'Astrobiology & Sample Return Prep',
    orbitType: 'Jezero Crater Surface / Orbit',
    visualTemplate: 'probe',
    color: 0xef4444,
    orbitalDistance: 4.6,
    orbitalPeriodDays: 1.0,
    M0: 2.4,
    orbitSpeed: 1.8,
    rotationSpeed: 0.01,
    diameter: '1,025 kg rover + 1.8 kg helicopter',
    orbitalPeriod: 'Mars surface operation',
    status: 'Active (Exploring Jezero Crater)',
    description: 'NASA flagship Mars 2020 rover exploring an ancient river delta in Jezero Crater to search for signs of ancient microbial life and collect rock samples.',
    significance: 'Deployed Ingenuity, the first powered aircraft to fly on another planet.'
  },
  {
    id: 'curiosity',
    name: 'Curiosity Rover',
    wikipediaTitle: 'Curiosity (rover)',
    category: 'artificial',
    layer: 'deep-space',
    parentBodyId: 'mars',
    launchYear: 2011,
    countryAgency: 'NASA / JPL',
    missionType: 'Mars Science Laboratory',
    orbitType: 'Gale Crater Surface / Orbit',
    visualTemplate: 'probe',
    color: 0xf59e0b,
    orbitalDistance: 5.0,
    orbitalPeriodDays: 1.0,
    M0: 4.1,
    orbitSpeed: 1.6,
    rotationSpeed: 0.01,
    diameter: '899 kg car-sized rover',
    orbitalPeriod: 'Mars surface operation',
    status: 'Active (Exploring Mount Sharp since 2012)',
    description: 'Car-sized rover exploring Gale Crater to investigate Martian climate, geology, and past habitability.',
    significance: 'Proved ancient Mars had liquid water lakes capable of supporting microbial life.'
  },
  {
    id: 'maven',
    name: 'MAVEN (Mars Atmosphere & Volatiles)',
    wikipediaTitle: 'MAVEN',
    category: 'artificial',
    layer: 'deep-space',
    parentBodyId: 'mars',
    launchYear: 2013,
    countryAgency: 'NASA',
    missionType: 'Martian Upper Atmosphere Probe',
    orbitType: 'Elliptical Mars Orbit',
    visualTemplate: 'probe',
    color: 0x38bdf8,
    orbitalDistance: 5.4,
    orbitalPeriodDays: 0.18,
    M0: 1.9,
    orbitSpeed: 1.5,
    rotationSpeed: 0.01,
    diameter: '11.4 m solar array span',
    orbitalPeriod: '4.5 hours',
    status: 'Active',
    description: 'Orbiter studying the loss of Mars\'s atmosphere to space via solar wind stripping over billions of years.',
    significance: 'Explained how Mars transitioned from a warm wet planet to a cold dry desert.'
  },

  // ============================================================
  // SUN & DEEP-SPACE LAGRANGE POINT OBSERVATORIES
  // ============================================================
  {
    id: 'aditya-l1',
    name: 'Aditya-L1',
    wikipediaTitle: 'Aditya-L1',
    category: 'artificial',
    layer: 'deep-space',
    parentBodyId: 'sun',
    launchYear: 2023,
    countryAgency: 'India (ISRO)',
    missionType: 'Solar Dynamics & Space Weather Observatory',
    orbitType: 'Sun-Earth L1 Halo Orbit (1.5 million km)',
    visualTemplate: 'telescope',
    color: 0xf97316,
    orbitalDistance: 18.0,
    orbitalPeriodDays: 177.0,
    M0: 1.4,
    orbitSpeed: 1.2,
    rotationSpeed: 0.01,
    diameter: '1,475 kg solar observatory bus',
    orbitalPeriod: '177 days (Halo Orbit around L1)',
    status: 'Active (Inserted into L1 Halo Orbit Jan 6, 2024)',
    description: "India's first dedicated solar space observatory stationed at the Sun-Earth L1 Lagrange point to observe the solar corona, coronal mass ejections (CMEs), and space weather.",
    significance: 'Uninterrupted 24/7 view of the Sun without eclipses.'
  },
  {
    id: 'james-webb',
    name: 'James Webb Space Telescope (JWST)',
    wikipediaTitle: 'James Webb Space Telescope',
    category: 'artificial',
    layer: 'deep-space',
    parentBodyId: 'sun',
    launchYear: 2021,
    countryAgency: 'NASA / ESA / CSA',
    missionType: 'Infrared Space Astronomy',
    orbitType: 'Sun-Earth L2 Halo Orbit (1.5 million km)',
    visualTemplate: 'telescope',
    color: 0xf59e0b,
    orbitalDistance: 22.0,
    orbitalPeriodDays: 180.0,
    M0: 3.8,
    orbitSpeed: 1.0,
    rotationSpeed: 0.005,
    diameter: '6.5 m beryllium mirror, 21 m sunshield',
    orbitalPeriod: '6 months (L2 Halo Orbit)',
    status: 'Active (Premier astrophysics observatory)',
    description: 'The premier space science observatory in history. Operating in deep infrared to observe the earliest stars and galaxies formed after the Big Bang and analyze exoplanet atmospheres.',
    significance: 'Unprecedented infrared resolution observing back 13.5 billion light-years.'
  },
  {
    id: 'parker-solar-probe',
    name: 'Parker Solar Probe',
    wikipediaTitle: 'Parker Solar Probe',
    category: 'artificial',
    layer: 'deep-space',
    parentBodyId: 'sun',
    launchYear: 2018,
    countryAgency: 'NASA / APL',
    missionType: 'Solar Corona Touch & Heliophysics',
    orbitType: 'Perihelion Solar Orbit (6.1 million km)',
    visualTemplate: 'probe',
    color: 0xef4444,
    orbitalDistance: 15.5,
    orbitalPeriodDays: 88.0,
    M0: 0.2,
    orbitSpeed: 2.2,
    rotationSpeed: 0.01,
    diameter: '11.4 cm carbon-composite heat shield',
    orbitalPeriod: '88 days',
    status: 'Active ("Touching the Sun")',
    description: 'Fastest human-made object in history (reaching 700,000 km/h). Flies directly through the Sun\'s outer atmosphere (corona).',
    significance: 'First spacecraft to fly through the solar corona.'
  },

  // ============================================================
  // OUTER PLANET PROBES (Jupiter, Saturn, Deep Space)
  // ============================================================
  {
    id: 'juno',
    name: 'Juno',
    wikipediaTitle: 'Juno (spacecraft)',
    category: 'artificial',
    layer: 'deep-space',
    parentBodyId: 'jupiter',
    launchYear: 2011,
    countryAgency: 'NASA / JPL',
    missionType: 'Jovian Magnetosphere & Core Probe',
    orbitType: 'Polar Jupiter Orbit',
    visualTemplate: 'probe',
    color: 0xf59e0b,
    orbitalDistance: 13.5,
    orbitalPeriodDays: 53.0,
    M0: 1.5,
    orbitSpeed: 1.4,
    rotationSpeed: 0.01,
    diameter: '20 m solar array span',
    orbitalPeriod: '53 days',
    status: 'Active (Orbiting Jupiter)',
    description: 'Solar-powered spacecraft orbiting Jupiter in a highly elliptical polar orbit to map its magnetic field, atmosphere depth, and core structure.',
    significance: 'Revealed shallow lightning and liquid metallic hydrogen layer inside Jupiter.'
  },
  {
    id: 'cassini',
    name: 'Cassini-Huygens',
    wikipediaTitle: 'Cassini–Huygens',
    category: 'artificial',
    layer: 'deep-space',
    parentBodyId: 'saturn',
    launchYear: 1997,
    countryAgency: 'NASA / ESA / ASI',
    missionType: 'Saturnian System Exploration',
    orbitType: 'Saturn System Orbit',
    visualTemplate: 'probe',
    color: 0x38bdf8,
    orbitalDistance: 12.5,
    orbitalPeriodDays: 16.0,
    M0: 4.2,
    orbitSpeed: 1.5,
    rotationSpeed: 0.01,
    diameter: '6.7 m length, 4 m high-gain dish',
    orbitalPeriod: '16 days',
    status: 'Completed Mission ("Grand Finale" Saturn plunge Sep 2017)',
    description: 'Flagship mission that explored Saturn, its rings, and complex moon system for 13 years. Deployed the Huygens probe onto Titan\'s surface.',
    significance: 'Discovered water ice plumes on Enceladus and methane lakes on Titan.'
  },
  {
    id: 'voyager-1',
    name: 'Voyager 1',
    wikipediaTitle: 'Voyager 1',
    category: 'artificial',
    layer: 'deep-space',
    parentBodyId: 'sun',
    launchYear: 1977,
    countryAgency: 'NASA / JPL',
    missionType: 'Interstellar Medium Exploration',
    orbitType: 'Hyperbolic Interstellar Trajectory (162 AU)',
    visualTemplate: 'probe',
    color: 0x38bdf8,
    orbitalDistance: 32.0,
    orbitalPeriodDays: 99999.0,
    M0: 0.1,
    orbitSpeed: 0.3,
    rotationSpeed: 0.01,
    diameter: '3.7 m parabolic high-gain dish',
    orbitalPeriod: 'Interstellar escape trajectory',
    status: 'Active (Furthest human-made object in history)',
    description: 'Space probe launched in 1977. Crossed the heliopause into interstellar space in August 2012, continuously transmitting scientific data back to Earth.',
    significance: 'First human object to enter interstellar space.'
  },
  {
    id: 'voyager-2',
    name: 'Voyager 2',
    wikipediaTitle: 'Voyager 2',
    category: 'artificial',
    layer: 'deep-space',
    parentBodyId: 'sun',
    launchYear: 1977,
    countryAgency: 'NASA / JPL',
    missionType: 'Grand Tour of Outer Planets',
    orbitType: 'Hyperbolic Interstellar Trajectory (136 AU)',
    visualTemplate: 'probe',
    color: 0x60a5fa,
    orbitalDistance: 30.0,
    orbitalPeriodDays: 99999.0,
    M0: 2.8,
    orbitSpeed: 0.35,
    rotationSpeed: 0.01,
    diameter: '3.7 m parabolic high-gain dish',
    orbitalPeriod: 'Interstellar escape trajectory',
    status: 'Active (Interstellar space)',
    description: 'The only spacecraft to visit all four gas giant planets (Jupiter, Saturn, Uranus, and Neptune). Entered interstellar space in 2018.',
    significance: 'Only probe to ever visit Uranus and Neptune.'
  }
];
